name = "PluginSystem"
uuid = "ff50533a-81a8-4b27-b8f2-3f95e4e4475a"
version = "0.1.0"
authors = ["chenzhiyuan"]

[workspace]
projects = ["test", "docs"]

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
JSON = "1.4.0"
LibGit2 = "1.11.0"
Markdown = "1.11.0"
Pkg = "1.12.1"
PrecompileTools = "1.2.1"
Preferences = "1.5.1"
SHA = "0.7.0"
Scratch = "1.3.0"
TOML = "1.0.3"
UUIDs = "1.11.0"

[apps.plugin]
